packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.39.1
  '@types/node': 22.19.1
  eslint: ^9.39.1
  jotai: 2.15.1
  lucide-react: 0.554.0
  motion: 12.23.24
  next: ^16.0.1
  sonner: ^2.0.7
  typescript: 5.9.2

catalogs:
  ai:
    '@ai-sdk/openai': ^2.0.71
    ai: ^5.0.98
  convex:
    '@convex-dev/agent': ^0.3.0
    convex: ^1.29.3
    convex-helpers: ^0.1.105
  form:
    '@hookform/resolvers': ^5.2.2
    react-hook-form: ^7.66.1
    zod: ^4.1.12
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: ^19.2.0
    react-dom: ^19.2.0
