import { ClerkClientProvider } from "@/providers/clerk-provider";
import { ConvexClientProvider } from "@/providers/convex-provider";
import { ThemeProvider } from "@repo/ui/components/theme/provider";
import { Toaster } from "@repo/ui/components/ui/sonner";
import type { Metadata } from "next";
import { Geist_Mono, Inter, Libre_Baskerville } from "next/font/google";

import "@repo/ui/globals.css";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});
const fontMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});
const fontSerif = Libre_Baskerville({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Konvo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} ${fontSerif.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          enableColorScheme
          disableTransitionOnChange
        >
          <ClerkClientProvider>
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </ClerkClientProvider>
          <Toaster closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
